### ISSUE TITLE
Invalid non-string/buffer chunk with optimize-images

### ISSUE THREAD

**Issue by git-no** [dimitri-koenig/jekyll-gulp-optimizations#1]
First, great plugin, thank you.

Since the last few days the gulp script fails and breaks with the error of optimize-images

```
hrow er; // Unhandled 'error' event
      ^
TypeError: Invalid non-string/buffer chunk
```

It seems these guys have a simular problem: [gulp-imagemin (jpegtran-bin and optipng-bin) doesn't build on customized](https://github.com/pcssi/docker-images/issues/1#issuecomment-149223621)

Beste Grüsse aus der Schweiz

**Comment by dimitri-koenig** [comment]
Hi Doc

I just updated all my dependencies and it still works like a charm.
Can you test again after updating all of your dependencies?
