### ISSUE TITLE
Noob in need of clarification

### ISSUE THREAD

**Issue by tterb** [dimitri-koenig/jekyll-gulp-optimizations#3]
This is in no way an issue, but more of an aspiration that you could help dumb down the necessary contents of the **gulpconfig.json** file for someone who's new to Gulp, CloudFlare, and pretty much web development as a whole.
I'm pretty sure I've managed to figure out what's needed in the *cloudflareToken*, *cloudflareEmail*, and *cloudflareDomain* fields, but where would I find the information for the *remoteServer* and *remotePath* fields. Also, if it helps, this is just for a GitHub profile page using Jekyll.
Thanks in advance!

**Comment by dimitri-koenig** [comment]
Hi Brett

You would need those two entries in case you want to sync your local files to a remote server via ssh. How do you copy your jekyll output files to your github profile page server?

**Comment by tterb** [comment]
Thanks for the response, I'm currently just using git and my *.github.io repository to make changes to my profile page server. Does that mean that these entries are unnecessary for me?

**Comment by dimitri-koenig** [comment]
Yes, that would be unnecessarily because GitHub uses the git repo directly

**Comment by tterb** [comment]
Okay, thanks. Your post and Steve Edson's article were very helpful as a first-time Gulp user!
