### ISSUE TITLE
forgot to include instructions to gitignore node_modules/

### ISSUE THREAD

**Issue by cauerego** [dimitri-koenig/jekyll-gulp-optimizations#4]
at least in my case, with not so basic github pages, I never had such a folder before. and it's sure a good idea to have it in `.gitignore`. ;)

**Comment by dimitri-koenig** [comment]
Thx, totally forgot it 2 years ago :-)

**Comment by cauerego** [comment]
wow, that was fast! :o

do you still use this, though?

I still couldn't get mine to work, got some gulp deploy issues and having 0 experience with gulp left to check it another day. :(
